### ISSUE TITLE
Wrong types for `kirbyup.import()`

### ISSUE THREAD

**Issue by arnoson** [johannschopplich/kirbyup#32]
Right now the `import` function has this signature:
```ts
import(modules: Record<string, Module>): Record<string, any>;
```
But the example suggest that using a blob-string instead of a modules record is possible. Which will result in typescript errors, or am I missing something (I guess the blob-string gets transformed into a record by vite)?
```ts
kirbyup.import('./components/blocks/*.vue')
```

**Comment by johannschopplich** [comment]
You guessed correctly, an internal Vite plugin will transform the following code in a first transformation step:

```diff
-kirbyup.import(<path>)
+kirbyup.import(import.meta.glob(<path>, { eager: true }))
```

Afterwards, Vite's [glob import](https://vitejs.dev/guide/features.html#glob-import) (transformation step 2) will handle resolving the JavaScript files. 

The typings are technically correct, but not for the user, since won't see any of the transformations applied. We should improve the typings. Good catch.

**Comment by arnoson** [comment]
Wow, thanks for the quick fix!
